set_attack_value(AT_DAIR2, AG_CATEGORY, 1);
set_attack_value(AT_DAIR2, AG_SPRITE, sprite_get("dair2"));
set_attack_value(AT_DAIR2, AG_NUM_WINDOWS, 4);
set_attack_value(AT_DAIR2, AG_HAS_LANDING_LAG, 1);
set_attack_value(AT_DAIR2, AG_LANDING_LAG, 8);
set_attack_value(AT_DAIR2, AG_HURTBOX_SPRITE, sprite_get("dair2_hurt"));

set_window_value(AT_DAIR2, 1, AG_WINDOW_TYPE, 1);
set_window_value(AT_DAIR2, 1, AG_WINDOW_LENGTH, 8);
set_window_value(AT_DAIR2, 1, AG_WINDOW_ANIM_FRAMES, 2);
set_window_value(AT_DAIR2, 1, AG_WINDOW_VSPEED, -1);
set_window_value(AT_DAIR2, 1, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_DAIR2, 1, AG_WINDOW_SFX, asset_get("sfx_swipe_medium1"));
set_window_value(AT_DAIR2, 1, AG_WINDOW_SFX_FRAME, 7);

set_window_value(AT_DAIR2, 2, AG_WINDOW_TYPE, 1);
set_window_value(AT_DAIR2, 2, AG_WINDOW_LENGTH, 4);
set_window_value(AT_DAIR2, 2, AG_WINDOW_ANIM_FRAMES, 1);
set_window_value(AT_DAIR2, 2, AG_WINDOW_ANIM_FRAME_START, 2);

set_window_value(AT_DAIR2, 3, AG_WINDOW_TYPE, 1);
set_window_value(AT_DAIR2, 3, AG_WINDOW_LENGTH, 12);
set_window_value(AT_DAIR2, 3, AG_WINDOW_ANIM_FRAMES, 3);
set_window_value(AT_DAIR2, 3, AG_WINDOW_ANIM_FRAME_START, 3);
set_window_value(AT_DAIR2, 3, AG_WINDOW_HAS_WHIFFLAG, 5);

set_window_value(AT_DAIR2, 4, AG_WINDOW_TYPE, 1);
set_window_value(AT_DAIR2, 4, AG_WINDOW_LENGTH, 7);
set_window_value(AT_DAIR2, 4, AG_WINDOW_ANIM_FRAMES, 1);
set_window_value(AT_DAIR2, 4, AG_WINDOW_ANIM_FRAME_START, 6);
set_window_value(AT_DAIR2, 4, AG_WINDOW_HAS_WHIFFLAG, 5);

set_num_hitboxes(AT_DAIR2, 4);

set_hitbox_value(AT_DAIR2, 1, HG_PARENT_HITBOX, 1);
set_hitbox_value(AT_DAIR2, 1, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_DAIR2, 1, HG_WINDOW, 2);
set_hitbox_value(AT_DAIR2, 1, HG_LIFETIME, 4);
set_hitbox_value(AT_DAIR2, 1, HG_HITBOX_X, 30);
set_hitbox_value(AT_DAIR2, 1, HG_HITBOX_Y, -10);
set_hitbox_value(AT_DAIR2, 1, HG_WIDTH, 38);
set_hitbox_value(AT_DAIR2, 1, HG_HEIGHT, 38);
set_hitbox_value(AT_DAIR2, 1, HG_SHAPE, 0);
set_hitbox_value(AT_DAIR2, 1, HG_PRIORITY, 1);
set_hitbox_value(AT_DAIR2, 1, HG_DAMAGE, 7);
set_hitbox_value(AT_DAIR2, 1, HG_ANGLE, 30);
set_hitbox_value(AT_DAIR2, 1, HG_BASE_KNOCKBACK, 5);
set_hitbox_value(AT_DAIR2, 1, HG_KNOCKBACK_SCALING, 0.45);
set_hitbox_value(AT_DAIR2, 1, HG_BASE_HITPAUSE, 8);
set_hitbox_value(AT_DAIR2, 1, HG_HITPAUSE_SCALING, 0.7);
set_hitbox_value(AT_DAIR2, 1, HG_VISUAL_EFFECT_Y_OFFSET, 20);
set_hitbox_value(AT_DAIR2, 1, HG_HIT_SFX, asset_get("sfx_blow_medium2"));

set_hitbox_value(AT_DAIR2, 2, HG_PARENT_HITBOX, 2);
set_hitbox_value(AT_DAIR2, 2, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_DAIR2, 2, HG_WINDOW, 2);
set_hitbox_value(AT_DAIR2, 2, HG_LIFETIME, 4);
set_hitbox_value(AT_DAIR2, 2, HG_HITBOX_X, 52);
set_hitbox_value(AT_DAIR2, 2, HG_HITBOX_Y, 12);
set_hitbox_value(AT_DAIR2, 2, HG_WIDTH, 44);
set_hitbox_value(AT_DAIR2, 2, HG_HEIGHT, 44);
set_hitbox_value(AT_DAIR2, 2, HG_SHAPE, 0);
set_hitbox_value(AT_DAIR2, 2, HG_PRIORITY, 1);
set_hitbox_value(AT_DAIR2, 2, HG_DAMAGE, 7);
set_hitbox_value(AT_DAIR2, 2, HG_ANGLE, 30);
set_hitbox_value(AT_DAIR2, 2, HG_BASE_KNOCKBACK, 5);
set_hitbox_value(AT_DAIR2, 2, HG_KNOCKBACK_SCALING, 0.45);
set_hitbox_value(AT_DAIR2, 2, HG_BASE_HITPAUSE, 8);
set_hitbox_value(AT_DAIR2, 2, HG_HITPAUSE_SCALING, 0.7);
set_hitbox_value(AT_DAIR2, 2, HG_VISUAL_EFFECT_Y_OFFSET, 20);
set_hitbox_value(AT_DAIR2, 2, HG_HIT_SFX, asset_get("sfx_blow_medium2"));

set_hitbox_value(AT_DAIR2, 3, HG_PARENT_HITBOX, 3);
set_hitbox_value(AT_DAIR2, 3, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_DAIR2, 3, HG_WINDOW, 2);
set_hitbox_value(AT_DAIR2, 3, HG_LIFETIME, 4);
set_hitbox_value(AT_DAIR2, 3, HG_HITBOX_X, 76);
set_hitbox_value(AT_DAIR2, 3, HG_HITBOX_Y, 36);
set_hitbox_value(AT_DAIR2, 3, HG_WIDTH, 50);
set_hitbox_value(AT_DAIR2, 3, HG_HEIGHT, 50);
set_hitbox_value(AT_DAIR2, 3, HG_SHAPE, 0);
set_hitbox_value(AT_DAIR2, 3, HG_PRIORITY, 1);
set_hitbox_value(AT_DAIR2, 3, HG_DAMAGE, 7);
set_hitbox_value(AT_DAIR2, 3, HG_ANGLE, 30);
set_hitbox_value(AT_DAIR2, 3, HG_BASE_KNOCKBACK, 5);
set_hitbox_value(AT_DAIR2, 3, HG_KNOCKBACK_SCALING, 0.45);
set_hitbox_value(AT_DAIR2, 3, HG_BASE_HITPAUSE, 8);
set_hitbox_value(AT_DAIR2, 3, HG_HITPAUSE_SCALING, 0.7);
set_hitbox_value(AT_DAIR2, 3, HG_VISUAL_EFFECT_Y_OFFSET, 20);
set_hitbox_value(AT_DAIR2, 3, HG_HIT_SFX, asset_get("sfx_blow_medium2"));

set_hitbox_value(AT_DAIR2, 4, HG_PARENT_HITBOX, 4);
set_hitbox_value(AT_DAIR2, 4, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_DAIR2, 4, HG_WINDOW, 2);
set_hitbox_value(AT_DAIR2, 4, HG_LIFETIME, 4);
set_hitbox_value(AT_DAIR2, 4, HG_HITBOX_X, 110);
set_hitbox_value(AT_DAIR2, 4, HG_HITBOX_Y, 56);
set_hitbox_value(AT_DAIR2, 4, HG_WIDTH, 36);
set_hitbox_value(AT_DAIR2, 4, HG_HEIGHT, 36);
set_hitbox_value(AT_DAIR2, 4, HG_SHAPE, 0);
set_hitbox_value(AT_DAIR2, 4, HG_PRIORITY, 1);
set_hitbox_value(AT_DAIR2, 4, HG_DAMAGE, 9);
set_hitbox_value(AT_DAIR2, 4, HG_ANGLE, 270);
set_hitbox_value(AT_DAIR2, 4, HG_BASE_KNOCKBACK, 6);
set_hitbox_value(AT_DAIR2, 4, HG_KNOCKBACK_SCALING, 0.6);
set_hitbox_value(AT_DAIR2, 4, HG_BASE_HITPAUSE, 9);
set_hitbox_value(AT_DAIR2, 4, HG_HITPAUSE_SCALING, 0.9);
set_hitbox_value(AT_DAIR2, 4, HG_VISUAL_EFFECT_Y_OFFSET, 20);
set_hitbox_value(AT_DAIR2, 4, HG_HIT_SFX, asset_get("sfx_blow_heavy1"));